# !include _camera/security_camera.yaml

- platform: generic
  name: ISS
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=4&size=500x300&maptype=roadmap&markers=anchor:center%7Cicon:https://example.com/images/satellite-variant.png%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
  limit_refetch_to_url_change: true

- name: Bilal Location
  platform: generic
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.saturnmqtt_neptunen4.attributes.latitude }},{{ states.device_tracker.saturnmqtt_neptunen4.attributes.longitude }}&zoom=15&size=1000x1000&maptype=roadmap&markers=color:blue%7Clabel:B%7C{{ states.device_tracker.saturnmqtt_neptunen4.attributes.latitude }},{{ states.device_tracker.saturnmqtt_neptunen4.attributes.longitude }}
  limit_refetch_to_url_change: true  


